### ISSUE TITLE
Last part of BCCAQ CanESM data missing

### ISSUE THREAD

**Issue by dspittlehouse** [pacificclimate/pdp#11] opened 2015-01-07 22:14 UTC
Downloaded BCCAQ CanESM8.5  version for 1951/01/01-2100/12/31. Obtained 0 to 55114 days of data (Tmax, Tmin and ppt) instead of 0 to 55151 days. This occurred for two groups of grid cells north of Vancouver. BCCAQ for Access and CNRM were OK for these cells.

**Comment by basilveerman** [comment] 2015-01-07 22:34
Hi Dave,

I've taken a look at the source data and it only has 55115 timesteps available. The metadata shows that it uses a 365 day calendar rather than a 'standard' calendar. I'm not too familiar with why this may be the case so I'll check in with Alex for more information and let you know.

**Comment by basilveerman** [comment] 2015-01-07 23:13
Hi Dave,

Alex has confirmed that yes, the calendar is the reason for differing timestep counts:

> BCCAQ relies directly on daily output from the driving GCM and hence respects the GCM's calendar. For CanESM2, this means a fixed 365_day calendar, for the Hadley Centre models, 360_day, etc.

> One the other hand, BCSD disaggregates monthly GCM outputs to daily by resampling from the historical daily record. In practice, this means that non-standard GCM calendars can all be "corrected" to be Gregorian.

Because it is properly noted in the metadata, programs like ncdump will still be able to correctly interpret dates to the max 2100-12-31. You'll see however that it's missing extra leap year days.

I'm going to close this issue, but if you have any other questions just let me know.

-Basil

**Closed by basilveerman** 2015-01-07 23:13 UTC
Labels: question
